$schemaver: 2.1
repo_url: https://github.com/byu-oit/edge-clients
software:
  - name: edge-clients
    type: Library
    aliases:
    short_description: This repository contains a number of Java clients that are reused through many applications. These should probably all be moved to their own repos at some point.
    assignment_group: gro:AD-Back End Technologies and Applications
    notes:
    maintained_by:
      - romrell4
      - yoshutch
    developed_by_byu: true
    links:
      system_documentation_url: https://github.com/byu-oit/edge-clients
      swagger_urls:
    microservice: false
    technologies_used:
      - Java
      - Maven
    stages:
      production:
        hosting_location: Other
        relationships:
          depends_on:
            db_read_only:
            # ApiKeyClient:
              - byuprd1
            # PersonBasic:
              - cesprd1
            software:
            # AcademicClient:
              # - https://api.byu.edu:443/domains/legacy/academic/registration/studentschedule/v1/
            # AuthClient:
              # - https://ws.byu.edu/authentication/services/rest/v1/ws/session
              # - https://ws.byu.edu/authentication/services/rest/v1/hmac/nonce
            # ChartBlock: Written by Tim Hirschi
              # - https://api.byu.edu:443/domains/erp/fs/chartfieldvalidation/v1
            # ControlDatesClient:
              # - https://api.byu.edu:443/domains/legacy/academic/controls/controldatesws/v1
            # CoreIdentityClient:
              # - https://api.byu.edu:443/domains/legacy/identity/person/PRO/personsummary/v1/
              # - https://api.byu.edu:443/domains/legacy/identity/person/personLookup/v1/
              # - https://api.byu.edu:443/domains/legacy/identity/access/ismember/v1/
            # CredentialClient:
              # - https://ws.byu.edu/authentication/services/rest/v1/ws/session
              # - https://ws.byu.edu/authentication/services/rest/v1/hmac/nonce
            # LearningSuiteClient:
              # - https://lsapi-dev.byu.edu/learningoutcomes
            # YPayClient:
              - Payment Manager WS Web Service Production
    data_sensitivity: confidential
